export const websites = [
  {
    id: 1,
    name: "FX Exchange",
    image: "/test.jpg",
    price: "#100,000",
    videoLink: "/",
    chatLink: "/",
    category: "Exchange Website",
  },
  {
    id: 2,
    name: "Anchor Capital",
    image: "/test.jpg",
    price: "#120,000",
    videoLink: "/",
    chatLink: "/",
    category: "Investment Website",
  },
  {
    id: 3,
    name: "Swiftcargo",
    image: "/test.jpg",
    price: "#90,000",
    videoLink: "/",
    chatLink: "/",
    category: "Consignment Website",
  },
  {
    id: 4,
    name: "Grant",
    image: "/test.jpg",
    price: "#150,000",
    videoLink: "/",
    chatLink: "/",
    category: "Grant Website",
  },
  {
    id: 5,
    name: "Real ES",
    image: "/test.jpg",
    price: "#250,000",
    videoLink: "/",
    chatLink: "/",
    category: "Real Estate Website",
  },
  {
    id: 6,
    name: "UX Exchange",
    image: "/test.jpg",
    price: "#110,000",
    videoLink: "/",
    chatLink: "/",
    category: "Exchange Website", // Added more to test back and forth
  },
];
