// data/websites.ts or websites.js
export const websites = [
  {
    id: 1,
    name: "ConsiTrack",
    image: "/consitrack.png",
    price: "#85,000",
    videoLink: "/videos/Consitrack.mp4",
    chatLink: "https://wa.me/message/4AJYUNZJISVAG1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 2,
    name: "Consyne",
    image: "/consyne.png",
    price: "#80,000",
    videoLink: "/videos/Consyne.mp4",
    chatLink: "https://wa.me/message/4AJYUNZJISVAG1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 3,
    name: "Delivra",
    image: "/delivra.png",
    price: "#85,000",
    videoLink: "/videos/Delivra.mp4",
    chatLink: "https://wa.me/message/4AJYUNZJISVAG1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 4,
    name: "Shipnetic",
    image: "/shipnetic.png",
    price: "#80,000",
    videoLink: "/videos/Shipnetic.mp4",
    chatLink: "https://wa.me/message/4AJYUNZJISVAG1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 5,
    name: "Swiftcargo",
    image: "/swiftcargo.png",
    price: "#90,000",
    videoLink: "/videos/Swiftcargo.mp4",
    chatLink: "https://wa.me/message/4AJYUNZJISVAG1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 6,
    name: "FX Exchange",
    image: "/fxexchange.png",
    price: "#75,000",
    videoLink: "/videos/fxexchange.mp4",
    chatLink: "https://wa.me/message/4AJYUNZJISVAG1",
    category: "Exchange Website",
  },
  {
    id: 7,
    name: "CB Exchange",
    image: "/cbexchange.png",
    price: "#70,000",
    videoLink: "/videos/cbexchange.mp4",
    chatLink: "https://wa.me/message/4AJYUNZJISVAG1",
    category: "Exchange Website",
  },
];
