// data/websites.ts or websites.js
export const websites = [
  {
    id: 1,
    name: "ConsiTrack",
    image: "/consitrack.png",
    price: "55$",
    videoLink: "/videos/Consitrack.mp4",
    chatLink: "https://wa.me/qr/MI6T5PWGO6EDI1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 2,
    name: "Consyne",
    image: "/consyne.png",
    price: "80$",
    videoLink: "/videos/Consyne.mp4",
    chatLink: "https://wa.me/qr/MI6T5PWGO6EDI1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 3,
    name: "Delivra",
    image: "/delivra.png",
    price: "60$",
    videoLink: "/videos/Delivra.mp4",
    chatLink: "https://wa.me/qr/MI6T5PWGO6EDI1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 4,
    name: "Shipnetic",
    image: "/shipnetic.png",
    price: "70$",
    videoLink: "/videos/Shipnetic.mp4",
    chatLink: "https://wa.me/qr/MI6T5PWGO6EDI1",
    category: "Consignment or Logistics Website",
  },
  {
    id: 5,
    name: "FX Exchange",
    image: "/fxexchange.png",
    price: "65$",
    videoLink: "/videos/fxexchange.mp4",
    chatLink: "https://wa.me/qr/MI6T5PWGO6EDI1",
    category: "Exchange Website",
  },
  {
    id: 6,
    name: "CB Exchange",
    image: "/cbexchange.png",
    price: "60$",
    videoLink: "/videos/cbexchange.mp4",
    chatLink: "https://wa.me/qr/MI6T5PWGO6EDI1",
    category: "Exchange Website",
  },
];
